import type { User, Group, Category, Document, AuditLog } from "./types";

export const mockUsers: User[] = [
  {
    id: "u1",
    name: "Carlos Silva",
    email: "owner@acdocs.com",
    role: "owner",
    groupIds: ["g1", "g2", "g3"],
    createdAt: "2025-01-15T10:00:00Z",
  },
  {
    id: "u2",
    name: "Ana Souza",
    email: "admin@acdocs.com",
    role: "admin",
    groupIds: ["g1", "g2"],
    createdAt: "2025-02-01T10:00:00Z",
  },
  {
    id: "u3",
    name: "Roberto Lima",
    email: "manager@acdocs.com",
    role: "manager",
    groupIds: ["g1"],
    createdAt: "2025-03-01T10:00:00Z",
  },
  {
    id: "u4",
    name: "Maria Santos",
    email: "user@acdocs.com",
    role: "user",
    groupIds: ["g2"],
    createdAt: "2025-03-15T10:00:00Z",
  },
  {
    id: "u5",
    name: "João Oliveira",
    email: "reader@acdocs.com",
    role: "reader",
    groupIds: ["g3"],
    createdAt: "2025-04-01T10:00:00Z",
  },
];

export const mockGroups: Group[] = [
  {
    id: "g1",
    name: "Administrativo",
    description: "Equipe administrativa",
    memberIds: ["u1", "u2", "u3"],
    categoryIds: ["c1", "c2", "c3"],
    createdAt: "2025-01-15T10:00:00Z",
  },
  {
    id: "g2",
    name: "Financeiro",
    description: "Equipe financeira",
    memberIds: ["u1", "u2", "u4"],
    categoryIds: ["c2", "c4"],
    createdAt: "2025-01-20T10:00:00Z",
  },
  {
    id: "g3",
    name: "Operacional",
    description: "Equipe operacional",
    memberIds: ["u1", "u5"],
    categoryIds: ["c3", "c5"],
    createdAt: "2025-02-01T10:00:00Z",
  },
];

export const mockCategories: Category[] = [
  {
    id: "c1",
    name: "Pessoal",
    icon: "User",
    parentId: null,
    sharedWithGroupIds: ["g1"],
    documentTypes: [
      { id: "dt1", name: "CPF", categoryId: "c1" },
      { id: "dt2", name: "RG", categoryId: "c1" },
      { id: "dt3", name: "CNH", categoryId: "c1" },
      { id: "dt4", name: "Comprovante de Residência", categoryId: "c1" },
      { id: "dt5", name: "Certidão de Nascimento", categoryId: "c1" },
      { id: "dt6", name: "Certidão de Casamento", categoryId: "c1" },
      { id: "dt7", name: "Passaporte", categoryId: "c1" },
    ],
    createdAt: "2025-01-15T10:00:00Z",
  },
  {
    id: "c2",
    name: "Fiscal e Tributário",
    icon: "Receipt",
    parentId: null,
    sharedWithGroupIds: ["g1", "g2"],
    documentTypes: [
      { id: "dt8", name: "CND Estadual", categoryId: "c2" },
      { id: "dt9", name: "CND Federal", categoryId: "c2" },
      { id: "dt10", name: "CND Trabalhista", categoryId: "c2" },
      { id: "dt11", name: "DARF", categoryId: "c2" },
      { id: "dt12", name: "GARE", categoryId: "c2" },
      { id: "dt13", name: "Inscrição Estadual", categoryId: "c2" },
      { id: "dt14", name: "IRPF", categoryId: "c2" },
      { id: "dt15", name: "Nota Fiscal de Produtor", categoryId: "c2" },
    ],
    createdAt: "2025-01-20T10:00:00Z",
  },
  {
    id: "c3",
    name: "Imóvel e Propriedade",
    icon: "Building",
    parentId: null,
    sharedWithGroupIds: ["g1", "g3"],
    documentTypes: [
      { id: "dt16", name: "CCIR", categoryId: "c3" },
      { id: "dt17", name: "Contrato de Arrendamento", categoryId: "c3" },
      { id: "dt18", name: "Contrato de Compra e Venda", categoryId: "c3" },
      { id: "dt19", name: "Contrato de Parceria", categoryId: "c3" },
      { id: "dt20", name: "Escritura Pública", categoryId: "c3" },
      { id: "dt21", name: "Georreferenciamento", categoryId: "c3" },
      { id: "dt22", name: "ITR (DIAT/DIAC)", categoryId: "c3" },
      { id: "dt23", name: "Matrícula do Imóvel", categoryId: "c3" },
    ],
    createdAt: "2025-02-01T10:00:00Z",
  },
  {
    id: "c4",
    name: "Financeiro e Crédito",
    icon: "Landmark",
    parentId: null,
    sharedWithGroupIds: ["g2"],
    documentTypes: [
      { id: "dt24", name: "Cédula de Crédito - Custeio", categoryId: "c4" },
      { id: "dt25", name: "Cédula de Crédito - Investimento", categoryId: "c4" },
      { id: "dt26", name: "Contrato de Barter", categoryId: "c4" },
      { id: "dt27", name: "CPR", categoryId: "c4" },
      { id: "dt28", name: "Custeio Agrícola", categoryId: "c4" },
      { id: "dt29", name: "Financiamento de Máquinas", categoryId: "c4" },
      { id: "dt30", name: "PROAGRO", categoryId: "c4" },
      { id: "dt31", name: "Seguro Agrícola", categoryId: "c4" },
    ],
    createdAt: "2025-02-10T10:00:00Z",
  },
  {
    id: "c5",
    name: "Operacional e Sanitário",
    icon: "Leaf",
    parentId: null,
    sharedWithGroupIds: ["g3"],
    documentTypes: [
      { id: "dt32", name: "Análise de Solo", categoryId: "c5" },
      { id: "dt33", name: "Certificado Fitossanitário", categoryId: "c5" },
      { id: "dt34", name: "DAE", categoryId: "c5" },
      { id: "dt35", name: "GTA", categoryId: "c5" },
      { id: "dt36", name: "Laudo Técnico", categoryId: "c5" },
      { id: "dt37", name: "Receituário Agronômico", categoryId: "c5" },
    ],
    createdAt: "2025-02-15T10:00:00Z",
  },
  {
    id: "c6",
    name: "Ambiental",
    icon: "Trees",
    parentId: null,
    sharedWithGroupIds: ["g1", "g3"],
    documentTypes: [
      { id: "dt38", name: "Averbação de Reserva Legal", categoryId: "c6" },
      { id: "dt39", name: "CAR", categoryId: "c6" },
      { id: "dt40", name: "EIA/RIMA", categoryId: "c6" },
      { id: "dt41", name: "Licença de Instalação (LI)", categoryId: "c6" },
      { id: "dt42", name: "Licença de Operação (LO)", categoryId: "c6" },
      { id: "dt43", name: "Licença Prévia (LP)", categoryId: "c6" },
      { id: "dt44", name: "Outorga de Água", categoryId: "c6" },
      { id: "dt45", name: "PRA", categoryId: "c6" },
    ],
    createdAt: "2025-03-01T10:00:00Z",
  },
];

export const mockDocuments: Document[] = [
  {
    id: "d1",
    name: "CNH - Carlos Silva",
    fileName: "cnh_carlos.pdf",
    fileSize: 245000,
    mimeType: "application/pdf",
    categoryId: "c1",
    documentTypeId: "dt3",
    uploadedById: "u1",
    currentVersion: 2,
    expiresAt: "2026-03-15T00:00:00Z", // Expira em março de 2026
    alertDaysBefore: 30,
    versions: [
      {
        id: "v1",
        documentId: "d1",
        version: 1,
        fileName: "cnh_carlos_v1.pdf",
        fileSize: 240000,
        uploadedById: "u1",
        createdAt: "2025-06-01T10:00:00Z",
      },
      {
        id: "v2",
        documentId: "d1",
        version: 2,
        fileName: "cnh_carlos_v2.pdf",
        fileSize: 245000,
        uploadedById: "u1",
        createdAt: "2025-08-15T10:00:00Z",
      },
    ],
    createdAt: "2025-06-01T10:00:00Z",
    updatedAt: "2025-08-15T10:00:00Z",
  },
  {
    id: "d2",
    name: "DARF - Março 2025",
    fileName: "darf_marco_2025.pdf",
    fileSize: 128000,
    mimeType: "application/pdf",
    categoryId: "c2",
    documentTypeId: "dt11",
    uploadedById: "u2",
    currentVersion: 1,
    expiresAt: "2026-02-25T00:00:00Z", // Expira em 4 dias (crítico)
    alertDaysBefore: 15,
    versions: [
      {
        id: "v3",
        documentId: "d2",
        version: 1,
        fileName: "darf_marco_2025.pdf",
        fileSize: 128000,
        uploadedById: "u2",
        createdAt: "2025-07-10T10:00:00Z",
      },
    ],
    createdAt: "2025-07-10T10:00:00Z",
    updatedAt: "2025-07-10T10:00:00Z",
  },
  {
    id: "d3",
    name: "Matrícula Fazenda Norte",
    fileName: "matricula_fazenda_norte.pdf",
    fileSize: 512000,
    mimeType: "application/pdf",
    categoryId: "c3",
    documentTypeId: "dt23",
    uploadedById: "u3",
    currentVersion: 1,
    // Sem data de expiração
    versions: [
      {
        id: "v4",
        documentId: "d3",
        version: 1,
        fileName: "matricula_fazenda_norte.pdf",
        fileSize: 512000,
        uploadedById: "u3",
        createdAt: "2025-08-01T10:00:00Z",
      },
    ],
    createdAt: "2025-08-01T10:00:00Z",
    updatedAt: "2025-08-01T10:00:00Z",
  },
  {
    id: "d4",
    name: "Análise de Solo - Talhão 5",
    fileName: "analise_solo_talhao5.pdf",
    fileSize: 890000,
    mimeType: "application/pdf",
    categoryId: "c5",
    documentTypeId: "dt32",
    uploadedById: "u4",
    currentVersion: 1,
    expiresAt: "2026-02-18T00:00:00Z", // Vencido (ontem)
    alertDaysBefore: 30,
    versions: [
      {
        id: "v5",
        documentId: "d4",
        version: 1,
        fileName: "analise_solo_talhao5.pdf",
        fileSize: 890000,
        uploadedById: "u4",
        createdAt: "2025-09-01T10:00:00Z",
      },
    ],
    createdAt: "2025-09-01T10:00:00Z",
    updatedAt: "2025-09-01T10:00:00Z",
  },
  {
    id: "d5",
    name: "CAR - Fazenda Norte",
    fileName: "car_fazenda_norte.pdf",
    fileSize: 340000,
    mimeType: "application/pdf",
    categoryId: "c6",
    documentTypeId: "dt39",
    uploadedById: "u1",
    currentVersion: 3,
    expiresAt: "2026-03-10T00:00:00Z", // Expira em ~18 dias (warning)
    alertDaysBefore: 30,
    versions: [
      {
        id: "v6",
        documentId: "d5",
        version: 1,
        fileName: "car_fazenda_norte_v1.pdf",
        fileSize: 320000,
        uploadedById: "u1",
        createdAt: "2025-05-01T10:00:00Z",
      },
      {
        id: "v7",
        documentId: "d5",
        version: 2,
        fileName: "car_fazenda_norte_v2.pdf",
        fileSize: 335000,
        uploadedById: "u2",
        createdAt: "2025-07-01T10:00:00Z",
      },
      {
        id: "v8",
        documentId: "d5",
        version: 3,
        fileName: "car_fazenda_norte_v3.pdf",
        fileSize: 340000,
        uploadedById: "u1",
        createdAt: "2025-09-15T10:00:00Z",
      },
    ],
    createdAt: "2025-05-01T10:00:00Z",
    updatedAt: "2025-09-15T10:00:00Z",
  },
];

export const mockAuditLogs: AuditLog[] = [
  {
    id: "al1",
    action: "login",
    userId: "u1",
    userName: "Carlos Silva",
    resourceType: "auth",
    resourceId: "u1",
    resourceName: "Carlos Silva",
    createdAt: "2026-02-18T08:00:00Z",
  },
  {
    id: "al2",
    action: "upload",
    userId: "u1",
    userName: "Carlos Silva",
    resourceType: "document",
    resourceId: "d5",
    resourceName: "CAR - Fazenda Norte",
    details: "Versão 3 enviada",
    createdAt: "2026-02-17T14:30:00Z",
  },
  {
    id: "al3",
    action: "view",
    userId: "u3",
    userName: "Roberto Lima",
    resourceType: "document",
    resourceId: "d3",
    resourceName: "Matrícula Fazenda Norte",
    createdAt: "2026-02-17T11:00:00Z",
  },
  {
    id: "al4",
    action: "download",
    userId: "u4",
    userName: "Maria Santos",
    resourceType: "document",
    resourceId: "d2",
    resourceName: "DARF - Março 2025",
    createdAt: "2026-02-16T16:45:00Z",
  },
  {
    id: "al5",
    action: "create",
    userId: "u2",
    userName: "Ana Souza",
    resourceType: "category",
    resourceId: "c6",
    resourceName: "Ambiental",
    createdAt: "2026-02-16T09:00:00Z",
  },
  {
    id: "al6",
    action: "update",
    userId: "u2",
    userName: "Ana Souza",
    resourceType: "group",
    resourceId: "g2",
    resourceName: "Financeiro",
    details: "Adicionado membro Maria Santos",
    createdAt: "2026-02-15T10:20:00Z",
  },
  {
    id: "al7",
    action: "upload",
    userId: "u4",
    userName: "Maria Santos",
    resourceType: "document",
    resourceId: "d4",
    resourceName: "Análise de Solo - Talhão 5",
    createdAt: "2026-02-15T08:00:00Z",
  },
  {
    id: "al8",
    action: "view",
    userId: "u5",
    userName: "João Oliveira",
    resourceType: "document",
    resourceId: "d5",
    resourceName: "CAR - Fazenda Norte",
    createdAt: "2026-02-14T15:30:00Z",
  },
];
